### ISSUE TITLE
Big files (5MB+) won't upload when posted

### ISSUE THREAD

**Issue by EdgyTwitterBoy** [CutoNaito/Niggod#9]
Uploading big files doesn't work which results in 404.
![image](https://user-images.githubusercontent.com/77931392/188846938-c585c201-04d9-431e-8c79-4bd7b8d42fef.png)

Uploaded image:
![ANIME-PICTURES NET_-_749351-2257x3984-hello!!!+love+live!-sunrise+(studio)-love+live!-tang+keke-aftamc-single](https://user-images.githubusercontent.com/77931392/188846987-2a0526b6-5246-4d4b-8ba8-918a980e8e4d.png)

**Comment by flowernal** [comment]
possible solution:
increase PHP file-upload size limit:

increase upload_max_filesize
increase post_max_size

**Comment by CutoNaito** [comment]
WEOOOO
